<div class="main">
		<div class="main-content container clearfix">
		<h1 class="the-title">
			Chính sách và điều khoản		</h1>

		<div class="the-content clearfix">
			<p><strong>1. Bản Quyền</strong></p>
<p>Tên, logo, tên sản phẩm, tên đặc tính, và khẩu hiệu Toyota đều là thương hiệu thuộc sở hữu hoặc đăng ký của <strong>Công ty Ô tô Toyota Việt Nam</strong> và/hoặc <strong>Toyota Việt Nam</strong>. Tất cả các quyền đều được bảo hộ. Những tài liệu có trên trang Web này không được phép sử dụng hoặc sao chép khi chưa có sự cho phép bằng văn bản của Toyota Việt Nam.</p>
<p><strong>2. Quyền thay đổi</strong></p>
<p>Tất cả những hình ảnh minh họa, thông tin, thông số kỹ thuật và giá cả được đề cập trên trang web này là chính xác vào thời điểm xây dựng trang web. Tuy nhiên, Công ty TNHH <strong>Toyota Việt Nam</strong> có quyền thay đổi hoặc hủy bỏ mẫu mã, đặc tính, thông số kỹ thuật, thiết kế và giá cả của sản phẩm được đề cập trên trang web này vào bất cứ thời điểm nào mà không cần phải thông báo trước. Luôn tham vấn Đại lý Toyota để có được thông tin mới nhất.</p>
<p>Những mẫu xe được mô tả trên trang web này có thể phù hợp với một hoặc nhiều phụ kiện bổ sung tùy chọn, bao gồm nhưng không giới hạn đối với mâm đúc hợp kim, đèn lái, thanh cản, thanh cứng kéo xe, đĩa tuabin và gương. B giá được đưa ra không bao gồm chi phí cho những phụ kiện bổ sung. Để biết thêm thông tin chi tiết, vui lòng liên hệ với Đại lý Toyota.</p>
<p>Do những thay đổi trong phần cứng và phần mềm máy vi tính, màu sắc thực tế của phương tiện có thể khác so với màu sắc của những sản phẩm được mô phỏng trên trang web này.</p>
<p><strong>3. Chính sách bảo mật</strong></p>
<p>Chúng tôi tôn trọng quyền riêng tư của quý vị.</p>
<p>Toyota Việt Nam thu thập thông tin từ người sử dụng tại một số thời điểm khác nhau trên trang Web. <strong>Toyota Việt Nam</strong> là chủ sở hữu duy nhất của những thông tin được thu thập trên trang web này. Chúng tôi sẽ không bán hoặc cho những người khác thuê những thông tin trên. Chúng tôi sẽ chỉ chia sẻ những thông tin trên cho các chi nhánh và đại lý của mình và những đối tác tiếp thị, quảng cáo đã ký hợp đồng làm việc dựa trên các tài liệu của chúng tôi (Như catalogue, brochure…).</p>
<p>Toyota Việt Nam sử dụng hai loại thông tin người dùng: thông tin ẩn danh được thu thập từ các tệp tin cookie, log và thông tin cá nhân quý vị cung cấp cho chúng tôi đối với những dịch vụ nhất định. Hãy xem những định nghĩa sau đây dành cho mỗi loại thông tin nói trên.</p>
<p><strong>4. Thông tin ẩn danh &#8211; Cookies và Log</strong></p>
<p>Cookie là một dạng dữ liệu được lưu trữ trên đĩa cứng của người dùng chứa những thông tin về người sử dụng. Cookie sẽ không có tác dụng kết nối với các thông tin cá nhân, cho đến lúc người sử dụng cung cấp thông tin đó (xem bên dưới). Nếu người sử dụng loại bỏ hoặc xóa cookie, anh ta vẫn có thể sử dụng trang web của chúng tôi. Hạn chế duy nhất của loại này đó là người sử dụng sẽ bị giới hạn trong một số vùng của trang web. Ví dụ, người sử dụng sẽ không thể nhận được thông báo chào hàng đặc biệt, hoặc không thể tham gia vào bất kỳ cuộc thi nào có thể diễn ra. Cookies cũng cho phép chúng tôi theo dõi và tập hợp chuỗi dữ liệu hành vi. Bằng cách này, chúng tôi có thể hướng tốt hơn đến mục tiêu quyền lợi của người sử dụng và nâng cao kinh nghiệm sử dụng của họ trên trang web của chúng tôi.</p>
<p>Toyota cũng chú trọng tới các tệp tin log tiêu chuẩn, ghi lại dữ liệu tất cả khách truy cập vào trang web này. Những tệp tin log này có thể bao gồm:</p>
<p>Miền Internet từ đó quý vị có thể truy cập vào trang web.</p>
<p>Địa chỉ IP của quý vị (Máy tính của quý vị được tự động cung cấp địa chỉ IP khi quý vị lướt Internet. Địa chỉ IP của quý vị hoặc tĩnh hoặc động. (Địa chỉ IP tĩnh quý vị có thể thiết lập; còn địa chỉ động thường không thể thiết lập lại).</p>
<p>Loại trình duyệt và hệ điều hành mà quý vị dùng.</p>
<p>Ngày giờ quý vị ghé thăm trang web.</p>
<p>Trang web mà quý vị đã xem.</p>
<p>Địa chỉ của trang Web mà quý vị liên kết tới.</p>
<p>Toyota sử dụng web log và thông tin thao tác kích chuột để giúp chúng tôi thiết kế trang web của mình, xác định những đặc điểm phổ biến của trang web và giúp trang web trở nên hữu dụng hơn đối với khách truy cập. Log web được ghi lại liên tục và thường chúng tôi không khai thác nhiều các thông tin từ những tệp tin log web này. Tuy nhiên, chúng tôi có thể sử dụng các tệp tin log web để xác định những cá nhân phá hoại, làm gián đoạn hoặc gây hư hỏng trang web của chúng tôi. Chúng tôi có thể chia sẻ thông tin nhật ký web với nhân viên thi hành pháp luật nếu chúng tôi tin có bằng chứng, hoặc bằng chứng về sự vi phạm luật pháp hoặc quy định của liên bang, nhà nước hoặc địa phương có khả năng xuất hiện.</p>
<p>Quảng cáo của Toyota tại những trang web khác không phải của Toyota có thể do các nhà cung cấp dịch vụ của Toyota thực hiện. Những nhà cung cấp này có thể sử dụng cookies để thu thập thông tin về những lần quý vị truy cập vào các trang web trên. Thông tin được thu thập có thể bao gồm những trang đã truy cập, ngày tháng, thông tin trình duyệt và/hoặc địa chỉ IP. Thông thường, chúng tôi không kết nối những thông tin cho cá nhân quý vị, ngoại trừ những trường hợp được quy định ở trên. Những thông tin này được thu thập nhằm giúp chúng tôi tùy chỉnh và đặt mục tiêu quảng cáo của mình theo nhu cầu và lợi ích của khách hàng. Nếu quý vị quyết định không muốn chúng tôi thu thập thông tin cho việc quảng cáo tại các trang web của bên thứ ba, vui lòng truy cập vào trang web của nhà cung cấp dịch vụ của chúng tôi hoặc yêu cầu từ chối</p>
<p><strong>5. Thông tin cá nhân tự nguyện</strong></p>
<p>Người sử dụng có thể lựa chọn thông tin cá nhân tự nguyện (tên, địa chỉ e-mail, số điện thoại, v.v…) nhằm giúp chúng tôi cung cấp những thông tin đó cho các dịch vụ như quảng cáo sản phẩm và trưng cầu ý kiến, những cuộc khảo sát và tranh luận, thông báo trang web, và những đề nghị đặc biệt tại thời điểm yêu cầu hoặc trong tương lai. Nếu trước đây quý vị đã cung cấp cho chúng tôi địa chỉ e-mail và không còn muốn nhận thông báo e-mail nữa, quý vị có thể dỡ tên mình khỏi danh sách e-mail của chúng tôi bằng cách gửi một e-mail đến địa chỉ webmaster@www.toyota.quangninh.vn,</p>
<p>Toyota không bán hoặc cho bên thứ ba thuê thông tin người sử dụng. Chúng tôi chia sẻ thông tin người sử dụng với các chi nhánh và đại lý của mình, và các đối tác tiếp thị thay mặt chúng tôi ký hợp đồng kinh danh (ví dụ, hoàn chỉnh sách quảng cáo). Khi người sử dụng ký giao kèo đối với những dịch vụ và chào hàng nhất định trên trang web của chúng tôi, chúng tôi sẽ chia sẻ tên, hoặc những thông tin liên lạc cần thiết khác cho bên hợp tác thứ ba để cung cấp những dịch vụ trên. Toyota sẽ chia sẻ thông tin người sử dụng phù hợp với chính sách bảo mật có hiệu lực tại thời điểm thu thập thông tin.</p>
<p>Nếu thông tin cá nhân của người sử dụng thay đổi, chúng tôi sẽ cố gắng đưa ra biện pháp để sửa hoặc cập nhật dữ liệu cá nhân của người sử dụng đó mà chúng tôi đã được cung cấp. Việc này có thể được thực hiện bằng cách gửi e-mail đến địa chỉ webmaster@www.toyota.quangninh.vn.</p>
<p><strong>6. Bảo mật</strong></p>
<p>Toyota thực hiện mọi phòng ngừa hợp lý nhằm bảo vệ thông tin người sử dụng, cả trong khi thông tin đang được truyền đi và sau khi chúng tôi nhận được thông tin đó. Khi người sử dụng điền thông tin nhạy cảm (ví dụ số an sinh xã hội) vào các mẫu đơn yêu cầu xác thực, thông tin đó được mã hóa và bảo vệ bởi kĩ thuật mã hóa SSL 128-bit, một tiêu chuẩn bảo mật đối với dành cho các tổ chức danh tiếng. Đồng thời, trên các trang web có mẫu đơn cần được bảo mật chạy trên các trình duyệt như Netscape Navigator và Microsoft Internet Explorer, biểu tượng “khóa” sẽ hiển thị trạng thái tăng cường bảo mật.</p>
<p>Hơn nữa, một khi chúng tôi đã nhận được thông tin, chúng tôi áp dụng những quy trình và chính sách bảo mật tố nhất bảo vệ dữ liệu thông tin cá nhân của quý vị khỏi mọi hành vi truy cập trái phép, phá hoại, sử dụng, chỉnh sửa và tiết lộ. Nếu quý vị có bất kỳ thắc mắc nào về bảo mật trên trang web của chúng tôi, quý vị có thể gửi e-mail đến địa chỉ webmaster@www.toyota.quangninh.vn</p>
<p><strong>7. Những liên kết</strong></p>
<p>Trang web này có những đường liên kết với các trang web khác. Xin vui lòng biết rằng Toyota Việt Nam không chịu trách nhiệm thực hiện bảo mật đối với những trang web đó. Chúng tôi khuyến khích người sử dụng nhận thức khi ra khỏi trang web của chúng tôi và đọc hướng dẫn bảo mật của mỗi trang web thu thập thông tin cá nhân. Hướng dẫn bảo mật này chỉ áp dụng với những thông tin do trang web này thu thập.</p>
<p><strong>8. Thông báo thay đổi</strong></p>
<p>Chúng tôi giữ quyền thay đổi chính sách bảo mật này vào bất kỳ thời điểm nào. Chúng tôi sẽ đăng tải những thay đổi đó lên trang web để người sử dụng luôn nhận thức những thông tin chúng tôi thu thập, cách thức chúng tôi sử dụng những thông tin đó và những trường hợp mà chúng tôi tiết lộ những thông tin đó. Chúng tôi sẽ sử dụng, chia sẻ và tiết lộ tất cả thông tin phù hợp với chính sách bảo mật có hiệu lực tại thời điểm thu thập thông tin.</p>
<p><strong>9. Tiết lộ những thông tin nhất định</strong></p>
<p>Toyota có thể tiết lộ bất kỳ dữ liệu nào, bất kể có thể nhận dạng cá nhân hay không, cho bất kỳ cá nhân nào thực hiện các dịch vụ kiểm toán, luật pháp, nghiệp vụ hoặc những dịch vụ tương tự khác cho Toyota. Bất kể khi nào có thể, chúng tôi sẽ yêu cầu người nhận thông tin cá nhân nhằm phục vụ những mục đích nói trên phải đồng ý bằng văn bản giữ bí mật thông tin, chỉ sử dụng thông tin vào mục đích được phép, trả lại hoặc hủy thông tin khi hoàn thành các dịch vụ.</p>
<p>Chúng tôi cũng có thể tiết lộ bất kỳ dữ liệu nào, bất kể có thể nhận dạng cá nhân hay không, khi được yêu cầu bởi trát đòi hầu tòa, lệnh hoặc trát của tòa án. Bất kể khi nào có thể, Toyota sẽ gửi e-mail cho người sử dụng thông báo rằng dữ liệu đó sẽ hoặc đã bị tiết lộ.</p>
<p>Chúng tôi cũng có thể tiết lộ bất kỳ dữ liệu nào, bất kể có thể nhận dạng cá nhân hay không, khi chúng tôi thấy việc tiết lộ đó cần thiết để bảo vệ an toàn của (i) một cá nhân, (ii) công chúng, hoặc (iii) an toàn và tin cậy của Toyota và/hoặc trang web này.</p>
<p><strong>10. Trẻ em</strong></p>
<p>Toyota không cho phép bất cứ ai dưới 13 tuổi tham gia vào bất kỳ dịch vụ nào trên trang web của mình yêu cầu phải khai báo các thông tin người sử dụng. Nếu chúng tôi biết rằng người sử dụng dưới 13 tuổi và đã trình nộp thông tin người sử dụng cho chúng tôi, chúng tôi sẽ xóa bỏ thông tin đó càng sớm càng tốt.</p>
		</div>
	</div>
	</div>